export default {
    uuid: null,
    id: null,
    tipo_identificacion: 'CC',
    identificacion: null,
    apellido1: null,
    apellido2: null,
    nombre1: null,
    nombre2: null,
    fecha_nacimiento: null,
    edad: null,
    sexo: null,
    medio_contacto: null,
    celular: null,
    celular2: null,
    email: null,
    codigo_departamento: null,
    codigo_municipio: null,
    zona: null,
    direccion: null,
    // etnia: null,
    condicion_desplazamiento: null,
    codigo_departamento_votacion: null,
    codigo_municipio_votacion: null,
    lugar_votacion: null,
    mesa_votacion: null,
    observaciones: null,
    user_id: null,
    sincronizado: false,
    /// objects
    departamento: null,
    municipio: null,
    departamento_votacion: null,
    municipio_votacion: null
}